services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: playBoard_improve_container
    volumes:
      - ../:/app
    command: tail -f /dev/null
    ports:
      - "8080:8080"
    networks:
      - backend-db
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: playBoard_improve_db_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    networks:
      - backend-db

networks:
  backend-db:
    name: backend-db
    driver: bridge